### ISSUE TITLE
yarn install fails by Node-gyp error

### ISSUE THREAD

**Issue by UmerMIB** [wednesday-solutions/node-express-graphql-template#127]
I tried several times to install all node modules but everytime I got `node-gyp` modules errors
tested Node versions
- 16.2
- 14.x

OS: Ubuntu 20.04

```error /home/umermib/Documents/codes/ainova/backend/node_modules/libpq: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/umermib/Documents/codes/ainova/backend/node_modules/libpq
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0```

**Comment by ijas-ws** [comment]
It looks like a system dependency error. We use 'pg-native' for bindings between node.js and PostgreSQL via libpq. It requires PostgreSQL client libraries and tools to be installed. If you are using Linux/Debian 'libpq-dev' should be installed on your machine.

  For installing libpq-dev globally, execute the following command
       sudo apt-get install libpq-dev
       
If you need more information about the same, please look into https://www.npmjs.com/package/pg-native
If you are facing other issues, please raise an issue and we'll look into them. Thanks

**Comment by UmerMIB** [comment]
> It looks like a system dependency error. We use 'pg-native' for bindings between node.js and PostgreSQL via libpq. It requires PostgreSQL client libraries and tools to be installed. If you are using Linux/Debian 'libpq-dev' should be installed on your machine.
> 
> For installing libpq-dev globally, execute the following command sudo apt-get install libpq-dev
> 
> If you need more information about the same, please look into https://www.npmjs.com/package/pg-native If you are facing other issues, please raise an issue and we'll look into them. Thanks

Thanks @ijas-ws I was to solve it by installing this pakage
